# SITE CONFIGURATION
baseurl: "/blog"
url: "https://samagra14.github.io"
title: The solitary reaper # site's title
description: "My life in general" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Type on Strap # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: CFC919D7671DD101B036109961CA2297 # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>You do not study mathematics because it helps you build a bridge. You study mathematics because it is the poetry of the universe. Its beauty transcends mere things.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: Glad to have met you.
  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: samagra14@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "samagra.sharma"
  flickr:
  gitlab:
  github: "samagra14"
  google_plus:
  instagram: "samagra14"
  keybase:
  linkedin: https://www.linkedin.com/in/samagra-sharma-4476bb135/  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "samagra_sharma" # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features
  google_analytics: "UA-118352996-1"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: true
  search: true
  tags: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true


# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
